heroes = {
    1: {"name": "Miya", "role": [ "Marksman" ], "skin": "Moonlight Archer", "skill": "Moon Arrow"},
    2: {"name": "Balmond", "role": [" Fighter" ], "skin": "Bloody Beast", "skill": "Cyclone Sweep"},
    3: {"name": "Saber", "role": [ "Assassin" ], "skin": "Wandering Sword", "skill": "Triple Sweep"},
    4: {"name": "Alice", "role": ["Mage","Tank"], "skin": "Queen of Blood", "skill": "Flowing Blood"},
    5: {"name": "Nana", "role": [ "Mage" ], "skin": "Sweet Leonin", "skill": "Molina Smooch"},
    6: {"name": "Tigreal", "role": [ "Tank" ], "skin": "Warrior of Dawn", "skill": "Implosion"},
    7: {"name": "Alucard", "role": ["Fighter","Assassin"], "skin": "Demon Hunter", "skill": "Fission Wave"},
    8: {"name": "Karina", "role": [ "Assassin" ], "skin": "Shadow Blade", "skill": "Dance of Blades"},
    9: {"name": "Akai", "role": [ "Tank" ], "skin": "Panda Warrior", "skill": "Heavy Spin"},
    10: {"name": "Franco", "role": ["Tank"], "skin": "Frozen Warrior", "skill": "Bloody Hunt"},
    11: {"name": "Bane", "role": ["Fighter","Mage"], "skin": "Frozen King", "skill": "Crab Claw Cannon"},
    12: {"name": "Bruno", "role": ["Marksman"], "skin": "The Protector", "skill": "Volley Shot"},
    13: {"name": "Clint", "role": ["Marksman"], "skin": "West Justice", "skill": "Grenade Bombardment"},
    14: {"name": "Rafaela", "role": ["Support"], "skin": "Wings of Holiness", "skill": "Light of Retribution"},
    15: {"name": "Eudora", "role": ["Mage"], "skin": "Lightning Weaver ", "skill": "Ball Lightning"},
    16: {"name": "Zilong", "role": ["Fighter","Assassin"], "skin": "Spear of the Dragon", "skill": "Spear Flip"},
    17: {"name": "Fanny", "role": ["Assassin"], "skin": "Blade Dancer", "skill": "Steel Cable"},
    18: {"name": "Layla", "role": ["Marksman"], "skin": "Energy Gunnner", "skill": "Destuction Rush"},
    19: {"name": "Minotaur", "role": ["Tank","Support"], "skin": "Son of Minos", "skill": "Minoan Fury"},
    20: {"name": "Lolita", "role": ["Tank","Support"], "skin": "Steel Elf", "skill": "Guarden's Reflection"},
    21: {"name":"Hayabusa", "role": [ "Assassin" ], "skin": "Crimson Shadow", "skill": "Ougi:Shadow Kill"},
    22: {"name":"Freya", "role": [ "Fighter" ], "skin": "Valkyrie", "skill": "Valkyrie Descent"},
    23: {"name":"Gord", "role": [ "Mage" ], "skin": "Professor of the Mystics", "skill": "Mystic Gush"},
    24: {"name":"Natalia", "role": [ "Assassin" ], "skin": "Bright Claw", "skill": "Smoke Bomb"},
    25: {"name":"Kagura", "role": [ "Mage" ], "skin": "Onmyouji Master", "skill": "Yin Yang Overturn"},
    26: {"name":"Chou", "role": [ "Fighter" ], "skin": "Kung Fu Boy", "skill": "The Way of Dragon"},
    27: {"name":"Sun", "role": [ "Fighter" ], "skin": "Monkey King", "skill": "Clone Techniques"},
    28: {"name":"Alpha", "role": [ "Fighter" ], "skin": "Blade of Enmity", "skill": "Force Swing"},
    29: {"name":"Ruby", "role": [ "Fighter" ], "skin": "Little Red Hood", "skill": "Be Good!"},
    30: {"name":"YiSunshin", "role": [ "Assassin","Marksman" ], "skin": "Paenlong Legend", "skill": "Blood Floods"},
    31: {"name":"Moskov", "role": [ "Marksman" ], "skin": "Spear of Quiescence", "skill": "Spear of Destruction"},
    32: {"name":"Johnson", "role": [ "Tank","Support" ], "skin": "Wild Engine", "skill": "Full Throttle"},
    33: {"name":"Cyclops", "role": [ "Mage" ], "skin": "Starsoul Magician", "skill": "Planets Attack"},
    34: {"name":"Estes", "role": [ "Support" ], "skin": "Moon Elf King", "skill": "Moonlight Immersion"},
    35: {"name":"Hilda", "role": [ "Fighter","Tank" ], "skin": "Power of Megalith", "skill": "Art of Hunting"},
    36: {"name":"Aurora", "role": [ "Mage" ], "skin": "Maiden of the Glacier", "skill": "Frigid Glacier"},
    37: {"name":"LapuLapu", "role": [ "Fighter" ], "skin": "Courageous Blade", "skill": "Land Shaker"},
    38: {"name":"Vexana", "role": [ "Mage" ], "skin": "Shimmer of Hope", "skill": "Eternal Guard"},
    39: {"name":"Roger", "role": [ "Fighter","Marksman" ], "skin": "Dire Wolf Hunter", "skill": "Lycan Pounce"},
    40: {"name":"Karrie", "role": [ "Marksman" ], "skin": "Lost Star", "skill": "Phantom Step"},
    41: {"name":"Gatotkaca", "role": [ "Tank","Fighter" ], "skin": "Mighty Legend", "skill": "Unbreakable"},
    42: {"name":"Harley", "role": [ "Mage","Assassin" ], "skin": "Mage Genius", "skill": "Poker Trick"},
    43: {"name":"Irithel", "role": [ "Marksman" ], "skin": "Jungle Heart", "skill": "Heavy Crossbow"},
    44: {"name":"Grock", "role": [ "Tank","Fighter" ], "skin": "Fortress Titan", "skill": "Guardian's Barrier"},
    45: {"name":"Argus", "role": [ "Fighter" ], "skin": "Dark Angel", "skill": "Eternal Evil"},
    46: {"name":"Odette", "role": [ "Mage" ], "skin": "Swan Princess", "skill": "Swan Song"},
    47: {"name":"Lancelot", "role": [ "Assassin" ], "skin": "Blade of Roses", "skill": "Thorned Rose"},
    48: {"name":"Diggie", "role": [ "Support" ], "skin": "Timekeeper", "skill": "Time Journey"},
    49: {"name":"Hylos", "role": [ "Tank" ], "skin": "Grand Warden", "skill": "Ring of Punishment"},
    50: {"name":"Zhask", "role": [ "Mage" ], "skin": "The king of Swarms", "skill": "Nightmartic Spawn"},
    51: {"name":"Helcurt", "role": [ "Assassin" ], "skin": "Shadowbringer", "skill": "Dark Night Falls"},
    52: {"name":"Pharsa", "role": [ "Mage" ], "skin": "Wings of Vengeance", "skill": "Wings by Wings"},
    53: {"name":"Lesley", "role": [ "Marksman","Assassin" ], "skin": "Deadly Sniper", "skill": "Ultimate Snipe"},
    54: {"name":"Jawhead", "role": [ "Fighter" ], "skin": "Steel Sweetheart", "skill": "Ejector"},
    55: {"name":"Angela", "role": [ "Support" ], "skin": "Bunnylove", "skill": "Heartguard"},
    56: {"name":"Gusion", "role": [ "Assasin" ], "skin": "Holy Blade", "skill": "Shadowblade Slaughter"},
    57: {"name":"Valir", "role": [ "Mage" ], "skin": "Son of Flames", "skill": "Burst Fireball"},
    58: {"name":"Martis", "role": [ "Fighter" ], "skin": "Asura King", "skill": "Decimation"},
    59: {"name":"Uranus", "role": [ "Tank" ], "skin": "Aethereal Defender", "skill": "Ionic Edge"},
    60: {"name":"Hanabi", "role": [ "Marksman" ], "skin": "Scarlet Flowers", "skill": "Ninjutus:Equinox"},
    61: {"name":"Change", "role": [ "Mage" ], "skin": "Moon Palace Immortal", "skill": "Meteor Shower"},
    62: {"name":"Kaja", "role": [ "Support","Fighter" ], "skin": "Nazar King", "skill": "Divine Judgment"},
    63: {"name":"Selena", "role": [ "Assassin","Mage" ], "skin": "Abyssal Witch", "skill": "Abyssal Arrow"},
    64: {"name":"Aldous", "role": [ "Fighter" ], "skin": "Soul Contractor", "skill": "Contract: Soul Steal"},
    65: {"name":"Claude", "role": [ "Marksman" ], "skin": "Master Thief", "skill": "Blazing Duet"},
    66: {"name":"Vale", "role": [ "Mage" ], "skin": "Windtalker", "skill": "Windstorm"},
    67: {"name":"Leomord", "role": [ "Fighter" ], "skin": "Sworn Sword", "skill": "Phantom Steed"},
    68: {"name":"Lunox", "role": [ "Mage" ], "skin": "Twilight Goddess", "skill": "Order & Chaos"},
    69: {"name":"Hanzo", "role": [ "Assassin" ], "skin": "Akuma Ninja", "skill": "Kinjutsu: Pinnacle Ninja"},
    70: {"name":"Belerick", "role": [ "Tank" ], "skin": "Guard of Nature", "skill": "Wrath of Dryad"},
    71: {"name":"Kimmy", "role": [ "Marksman","Mage" ], "skin": "Jetpack Rebel", "skill": "Energy Transformation"},
    72: {"name":"Thamuz", "role": [ "Fighter" ], "skin": "Lord Lava", "skill": "Molten Scythes"},
    73: {"name":"Harith", "role": [ "Mage" ], "skin": "Time Traveler", "skill": "Zaman Force"},
    74: {"name":"Minsitthar", "role": [ "Fighter" ], "skin": "Courageous Warrior", "skill": "Spear of Glory"},
    75: {"name":"Kadita", "role": [ "Mage","Assassin" ], "skin": "Ocean Goddess", "skill": "Rough Waves"},
    76: {"name":"Faramis", "role": [ "Mage","Support" ], "skin": "Soul Binder", "skill": "Nether Realm"},
    77: {"name":"Badang", "role": [ "Fighter" ], "skin": "Tribal Warrior", "skill": "Fist Wind"},
    78: {"name":"Khufra", "role": [ "Tank" ], "skin": "Desert Tyrant", "skill": "Bouncing Ball"},
    79: {"name":"Granger", "role": [ "Marksman" ], "skin": "Death Chanter", "skill": "Death Sonata"},
    80: {"name":"Guinevere", "role": [ "Fighter" ], "skin": "Ms. Violet", "skill": "Violet Requiem"},
    81: {"name":"Esmeralda", "role": [ "Tank","Mage" ], "skin": "Astrologer", "skill": "Frostmoon Shield"},
    82: {"name":"Terizla", "role": [ "Tank","Fighter" ], "skin": "Executioner", "skill": "Penalty Zone"},
    83: {"name":"XBorg", "role": [ "Fighter" ], "skin": "Firaga Armor", "skill": "Last Insanity"},
    84: {"name":"Ling", "role": [ "Assassin" ], "skin": "Cyan Finch", "skill": "Tempest of Blades"},
    85: {"name":"Dyrroth", "role": [ "Fighter" ], "skin": "Prince of the Abyss", "skill": "Abysm Strike"},
    86: {"name":"Lylia", "role": [ "Mage" ], "skin": "Little Witch", "skill": "Black Shoes"},
    87: {"name":"Baxia", "role": [ "Tank" ], "skin": "Mystic Tortoise", "skill": "Shield of Spirit"},
    88: {"name":"Masha", "role": [ "Fighter","Tank" ], "skin": "Wild-oats Fist", "skill": "Thunderclap"},
    89: {"name":"Wanwan", "role": [ "Marksman" ], "skin": "Agile Tiger", "skill": "Crossbow of Tang"},
    90: {"name":"Silvanna", "role": [ "Fighter" ], "skin": "Imperial Knightess", "skill": "Imperial Justice"},
    91: {"name":"Cecilion", "role": [ "Mage" ], "skin": "Embrace of Night", "skill": "Bats Feast"},
    92: {"name":"Carmilla", "role": [ "Tank","Support" ], "skin": "Shadow of Twilight", "skill": "Curse of Blood"},
    93: {"name":"Atlas", "role": [ "Tank" ], "skin": "Ocean Gladiator", "skill": "Fatal Links"},
    94: {"name":"PopolandKupa", "role": [ "Marksman" ], "skin": "Icefield Companions", "skill": "We Are Angry!"},
    95: {"name":"YuZhong", "role": [ "Fighter" ], "skin": "Black Drgon", "skill": "Black Dragon Form"},
    96: {"name":"LuoYi", "role": [ "Mage" ], "skin": "Yin-Yang Geomancer", "skill": "Diversion"},
    97: {"name":"Benedetta", "role": [ "Assassin","Fighter" ], "skin": "Shadow Ranger", "skill": "Alecto: Final Blow"},
    98: {"name":"Khaleed", "role": [ "Fighter" ], "skin": "Desert Scimitar", "skill": "Raging Sandstorm"},
    99: {"name":"Barats", "role": [ "Tank","Fighter" ], "skin": "Dino Rider", "skill": "Detona's Welcome"},
    100: {"name":"Brody", "role": [ "Marksman" ], "skin": "The Lone Star", "skill": "Torn-Apart Memory"},
    101: {"name":"Yve", "role": [ "Mage" ], "skin": "Astrowarden", "skill": "Real World Manipulation"},
    102: {"name":"Mathilda", "role": [ "Support","Assassin" ], "skin": "Swift Plume", "skill": "Circling Eagle"},
    103: {"name":"Paquito", "role": [ "Fighter","Assassin" ], "skin": "The Heavenly Fist", "skill": "Knockout Strike"},
    104: {"name":"Gloo", "role": [ "Tank" ], "skin": "Swamp Spirits", "skill": "Split, Split"},
    105: {"name":"Beatrix", "role": [ "Marksman" ], "skin": "Dawnbreak Soldier", "skill": "Masterful Gunner"},
    106: {"name":"Phoveus", "role": [ "Fighter" ], "skin": "Chains of Sin", "skill": "Infernal Pursuit"},
    107: {"name":"Natan", "role": [ "Marksman" ], "skin": "Spacetime Walker", "skill": "Entropy?"},
    108: {"name":"Aulus", "role": [ "Fighter" ], "skin": "Warrior of Ferocity", "skill": "Undying Fury"},
    109: {"name":"Aamon", "role": [ "Assassin" ], "skin": "Duke of Shards", "skill": "Endless Shards"},
    110: {"name":"Valentina", "role": [ "Mage" ], "skin": "Prophetess of the Night", "skill": "I Am You"},
    111: {"name":"Edith", "role": [ "Tank","Marksman" ], "skin": "Ancient Guard", "skill": "Primal Wrath"},
    112: {"name":"Floryn", "role": [ "Support" ], "skin": "The Budding Hope", "skill": "Bloom"},
    113: {"name":"Yin", "role": [ "Assassin","Fighter" ], "skin": "Martial Genius", "skill": "My Turn"},
    114: {"name":"Melissa", "role": [ "Marksman" ], "skin": "Cursed Needle", "skill": "Go Away!"},
    115: {"name":"Xavier", "role": [ "Mage" ], "skin": "Defier of Light", "skill": "Dawning Light"},
    116: {"name":"Julian", "role": [ "Mage","Fighter" ], "skin": "Scarlet Raven", "skill": "Smith's Legacy"},
    117: {"name":"Fredrinn", "role": [ "Fighter","Tank" ], "skin": "Rogue Appraiser", "skill": "Appraiser's Wrath"},
    118: {"name":"Joy", "role": [ "Assassin" ], "skin": "Flash of Miracle", "skill": "Ha, Electrifying Beats!"},
    119: {"name":"Novaria", "role": [ "Mage" ], "skin": "Star Rebel", "skill": "Astral Recall"},
    120: {"name":"Arlott", "role": [ "Fighter","Assassin" ], "skin": "Lone Lancer", "skill": "Final Slash"},
    121: {"name":"Ixia", "role": [ "Marksman" ], "skin": "Arclight Outlaw", "skill": "Full Barrage"},
    122: {"name":"Nolan", "role": [ "Assassin" ], "skin": "Cosmic Wayfinder", "skill": "Fracture"},
    123: {"name":"Cici", "role": [ "Fighter" ], "skin": "Bouyant Performer", "skill": "Yo-Yo Blitz"},
    124: {"name":"Chip", "role": [ "Support","Tank" ], "skin": "Phase Technician", "skill": "Why Walk?"},
    125: {"name":"Zhuxin", "role": [ "Mage" ], "skin": "Beacon of Spirits", "skill": "Crimson Beacon"},
    126: {"name":"Suyou", "role": [ "Fighter","Assassin" ], "skin": "Mask of the Immortal", "skill": "Evil Queller"},
}
